# Basic Information 
title: Soomin Chung
position: M.S. in Biomedical Engineering
affiliation: Seoul National University
affiliation_link: https://bioeng.snu.ac.kr/en/
email: soomin.chung.9910@gmail.com

# Search Engine Optimization (SEO)
keywords: Soomin Chung, Medical AI, Multimodal Learning, Clinical Data, Deep Learning, EHR, ECG, Bio-singal
canonical: https://soominchung.github.io/
description: Personal homepage of Soomin Chung – Researcher in AI4Health.

# The option is used to enable the MPI Informatics template.
enable_mpi_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?user=0PojgyMAAAAJ&hl=ko
cv_link: assets/files/SoominChung_CV.pdf
github_link: https://github.com/SoominChung
linkedin: https://www.linkedin.com/in/soominchung9910
#twitter: https://twitter.com/

# Images 
avatar: assets/img/soomin.jpg
favicon: ./assets/img/leaf.png
favicon_dark: ./assets/img/leaf.png

# Footnotes
enable_footnote: true

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
